// Mock data for Vercajkovna

const CATEGORIES = [
  { id: 'all', label: 'Všechno', glyph: '◍' },
  { id: 'stavba', label: 'Stavba', glyph: '▲' },
  { id: 'dilna', label: 'Dílna', glyph: '◆' },
  { id: 'udrzba', label: 'Údržba', glyph: '●' },
  { id: 'mereni', label: 'Měření', glyph: '│' },
  { id: 'ostatni', label: 'Ostatní', glyph: '◌' },
];

// Real photos from Unsplash for hero listings
const LISTINGS = [
  {
    id: 'festool-ts55',
    title: 'Ponorná pila Festool TS 55',
    subtitle: 'S vodicí lištou 1400 mm',
    price: 450, deposit: 3000,
    location: 'Praha 7 — Letná', distance: 1.2,
    rating: 4.9, reviews: 31,
    category: 'dilna',
    owner: { name: 'Tomáš', initial: 'T', since: '2023', rating: 4.8 },
    photo: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&q=80',
    badges: ['Top hodnocení', 'Rychle odpovídá'],
    description: 'Přesná ponorná pila pro řezání laminovaných desek, podlah i masivu. Pila jede jako hodinky, řez je čistý bez otřepů. Přibalím i vodicí lištu 1400 mm, paralelní doraz a náhradní pilový kotouč na dřevo.',
    available: true,
  },
  {
    id: 'makita-drill',
    title: 'Aku vrtačka Makita 18V',
    subtitle: '2× baterie 4Ah + nabíječka',
    price: 180, deposit: 1500,
    location: 'Praha 10 — Vršovice', distance: 3.4,
    rating: 4.7, reviews: 58,
    category: 'stavba',
    owner: { name: 'Michal', initial: 'M', since: '2024', rating: 4.9 },
    photo: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=800&q=80',
    badges: ['Oblíbené'],
    description: 'Klasika do garáže. Dvě nabité baterie + nabíječka, chuck bez klíče, kufřík. Sadu bitů nepůjčuju — není to moje, je to od táty.',
    available: true,
  },
  {
    id: 'karcher-wash',
    title: 'Vysokotlaký čistič Kärcher K5',
    subtitle: 'Na auto, dlažbu, fasádu',
    price: 290, deposit: 2000,
    location: 'Praha 4 — Chodov', distance: 5.1,
    rating: 4.8, reviews: 22,
    category: 'udrzba',
    owner: { name: 'Lucie', initial: 'L', since: '2024', rating: 4.9 },
    photo: 'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?w=800&q=80',
    badges: ['Doporučujeme'],
    description: 'K5 Premium. Bere 145 bar, naplní kbelík fakt rychle. Hadice 8 m, rotační tryska přibalená. V létě je o něj zájem, rezervujte dopředu.',
    available: true,
  },
  {
    id: 'laser-level',
    title: 'Křížový laser Bosch GLL 3-80',
    subtitle: 'Samonivelační, 3× 360°',
    price: 220, deposit: 2500,
    location: 'Praha 6 — Dejvice', distance: 4.0,
    rating: 4.9, reviews: 15,
    category: 'mereni',
    owner: { name: 'Petr', initial: 'P', since: '2023', rating: 4.7 },
    photo: 'https://images.unsplash.com/photo-1609205807490-89c0d65b63f6?w=800&q=80',
    badges: ['Profi'],
    description: 'Tři plné laserové roviny, samonivelace do 4°. Použitelný pro SDK stropy, obklady i venku se stativem. Stativ k dispozici za příplatek 50 Kč/den.',
    available: true,
  },
  {
    id: 'hilti-breaker',
    title: 'Bourací kladivo Hilti TE 1000',
    subtitle: 'Na beton, dlažbu, zdi',
    price: 680, deposit: 5000,
    location: 'Praha 9 — Vysočany', distance: 6.8,
    rating: 4.6, reviews: 12,
    category: 'stavba',
    owner: { name: 'Honza', initial: 'H', since: '2022', rating: 4.8 },
    photo: 'https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800&q=80',
    badges: ['Těžká kategorie'],
    description: 'Kladivo váží svoje, ale práci odvede. Vhodné na bourání příček a odsekávání dlažby. Půjčuji jen zkušeným — předám s instrukcí.',
    available: true,
  },
  {
    id: 'miter-saw',
    title: 'Pokosová pila DeWalt DWS 774',
    subtitle: 'Dvojité pokosení, 216 mm kotouč',
    price: 320, deposit: 2500,
    location: 'Praha 5 — Smíchov', distance: 2.8,
    rating: 4.8, reviews: 19,
    category: 'dilna',
    owner: { name: 'Radek', initial: 'R', since: '2024', rating: 4.9 },
    photo: 'https://images.unsplash.com/photo-1609587312208-cea54be969e7?w=800&q=80',
    badges: ['Novinka'],
    description: 'Čerstvě servisovaná pila, kotouč ostrý. Ideální na obložky, lišty a rámy. Přibalím i náhradní kotouč na hliník.',
    available: false,
  },
  {
    id: 'scaffold',
    title: 'Hliníkové lešení 4 m',
    subtitle: 'Pracovní výška až 6 m',
    price: 390, deposit: 3500,
    location: 'Praha 3 — Žižkov', distance: 2.1,
    rating: 4.7, reviews: 9,
    category: 'stavba',
    owner: { name: 'Vašek', initial: 'V', since: '2023', rating: 4.8 },
    photo: 'https://images.unsplash.com/photo-1581092795360-fd1ca04f0952?w=800&q=80',
    badges: [],
    description: 'Stabilní hliníkové lešení na kolečkách. Sestavení vysvětlím. Vejde se i do výtahu po rozložení.',
    available: true,
  },
  {
    id: 'heat-gun',
    title: 'Horkovzdušná pistole Metabo',
    subtitle: '2000 W, 2 stupně',
    price: 110, deposit: 800,
    location: 'Praha 2 — Vinohrady', distance: 1.8,
    rating: 4.6, reviews: 27,
    category: 'udrzba',
    owner: { name: 'Jana', initial: 'J', since: '2024', rating: 4.9 },
    photo: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    badges: ['Levně'],
    description: 'Na odstraňování laků, svařování fólií nebo rozehřívání zámků v zimě. Kufřík a pár trysek.',
    available: true,
  },
];

const DEMO_ACCOUNTS = [
  { name: 'Tomáš Novák', email: 'tomas@vercajkovna.cz', initial: 'T', role: 'Kutil z Letné' },
  { name: 'Lucie Kratochvílová', email: 'lucie@vercajkovna.cz', initial: 'L', role: 'Pořádková četa' },
  { name: 'Michal Dvořák', email: 'michal@vercajkovna.cz', initial: 'M', role: 'Stavebník na neděli' },
  { name: 'Petr Svoboda', email: 'petr@vercajkovna.cz', initial: 'P', role: 'Táta v garáži' },
];

const CONVERSATIONS = [
  {
    id: 'c1',
    with: { name: 'Tomáš N.', initial: 'T' },
    listing: 'Ponorná pila Festool TS 55',
    lastMessage: 'Super, v sobotu v 10 u mě na Letné.',
    time: '10:42',
    unread: 1,
    messages: [
      { from: 'them', text: 'Ahoj, pila je ještě volná na ten víkend?', time: '9:20' },
      { from: 'me', text: 'Ahoj, jo je. Potřebuješ i vodicí lištu?', time: '9:45' },
      { from: 'them', text: 'Lištu i paralelní doraz, kdyžtak. Můžu přijet v sobotu ráno?', time: '10:30' },
      { from: 'me', text: 'Super, v sobotu v 10 u mě na Letné.', time: '10:42' },
    ],
  },
  {
    id: 'c2',
    with: { name: 'Lucie K.', initial: 'L' },
    listing: 'Vysokotlaký čistič Kärcher K5',
    lastMessage: 'Dík! Vrátím ještě dneska do 18.',
    time: 'Út',
    unread: 0,
    messages: [
      { from: 'them', text: 'Díky za rychlé vyzvednutí!', time: 'Po 8:10' },
      { from: 'me', text: 'Není zač, vercajk je v pohodě 🙂', time: 'Po 8:30' },
      { from: 'them', text: 'Dík! Vrátím ještě dneska do 18.', time: 'Út' },
    ],
  },
  {
    id: 'c3',
    with: { name: 'Michal D.', initial: 'M' },
    listing: 'Aku vrtačka Makita 18V',
    lastMessage: 'Baterie jsou nabité?',
    time: 'Pá',
    unread: 2,
    messages: [
      { from: 'them', text: 'Čau, mám zájem o vrtačku na víkend.', time: 'Čt' },
      { from: 'them', text: 'Baterie jsou nabité?', time: 'Pá' },
    ],
  },
];

const VALUES = [
  { title: 'Sousedi si pomáhají', body: 'Půjčuješ od lidí z okolí. Žádní prostředníci — jen domluva, předání, díky.' },
  { title: 'Vercajk nemá spát v šuplíku', body: 'Jedna aku vrtačka se zahálí v garáži. Stovka jich pomůže udělat práci po celé čtvrti.' },
  { title: 'Poctivě, s důvěrou', body: 'Kauce, hodnocení, ověřené profily. Ale hlavně — lidi, kteří vědí, co je slušnost.' },
];

const FAQ = [
  { q: 'Jak si půjčím nářadí?', a: 'Najdi inzerát, vyber termín, pošli žádost. Majitel ji do 24 h schválí nebo zamítne. Po schválení zaplatíš a domluvíte si předání.' },
  { q: 'Kdo ručí za poškození?', a: 'Každý inzerát má kauci — ta kryje běžná poškození. V případě vážnější škody nás zkontaktuj, pomůžeme to vyřešit.' },
  { q: 'Jak probíhá platba?', a: 'Platíš přes platformu — kartou nebo převodem. Peníze majitel dostane až po potvrzení předání. Kauci vracíme do 3 dnů po vrácení vercajku.' },
  { q: 'Můžu vercajk pronajmout i já?', a: 'Samozřejmě. Klikni na „+" v tržišti, projdi tři kroky inzerce a za pět minut jsi v nabídce.' },
  { q: 'Co když se majitel neozve?', a: 'Pokud do 24 h nedorazí odpověď, žádost automaticky vyprší a nic neplatíš. Dáme ti vědět.' },
  { q: 'Je to opravdu všechno zadarmo?', a: 'Pro majitele je inzerce zdarma. Od nájemce si bereme malou provizi (cca 8 %), z které platíme provoz a podporu.' },
];

Object.assign(window, { CATEGORIES, LISTINGS, DEMO_ACCOUNTS, CONVERSATIONS, VALUES, FAQ });
